### ISSUE TITLE
invfx 잘못된 정보 수정 요청

### ISSUE THREAD

**Issue by myoun** [monun-docs/monun-docs#120]
![image](https://user-images.githubusercontent.com/76814120/213383122-5b8be173-61b4-43b2-adb5-f07eea0df132.png)
[Invfx 윈도우 생성하기#아이템 설정](https://monun.me/libraries/invfx/inventory-creation#%EC%95%84%EC%9D%B4%ED%85%9C-%EC%84%A4%EC%A0%95)을 보시면, 위와 같이 좌표가 1부터 시작합니다만... 실 코드에서는 0부터 시작하는걸로 보입니다.

**Comment by dolphin2410** [comment]
.....

**Comment by dolphin2410** [comment]
그림 다시 그려야겠네요ㅜㅜ. 제보 감사합니다

**Comment by dolphin2410** [comment]
# InvFX 그림 변천사

### 1
![1](https://user-images.githubusercontent.com/80996692/139722035-f8411a62-caa9-48e9-bcad-c2c68df5a9f9.png)

### 2
![2](https://user-images.githubusercontent.com/80996692/213830567-8bf7ed77-da60-485c-9d82-138839e1f56d.png)

### 3
![3](https://user-images.githubusercontent.com/80996692/213830592-be9d0f32-8b9d-4ee6-bd14-51ed19a46ed1.png)

**Comment by dolphin2410** [comment]
![스크린샷_20230121_100354](https://user-images.githubusercontent.com/80996692/213831008-03c59b9c-2604-4c2e-b2b1-305152f50dab.png)
적용 완료^^

**Comment by dolphin2410** [comment]
@myoun 확인되면 닫아주세요

**Comment by dolphin2410** [comment]
그냥 제가 닫을게요. 문제 있으면 다시 열어주세요
