### ISSUE TITLE
README.md에 있는 디스코드 주소 만료, Tap 이벤트 리스너 관련 문서 요청

### ISSUE THREAD

**Issue by faiz36** [monun-docs/monun-docs#121]
README.md에 있는 디스코드 링크가 만료되어있습니다,
TODO에 Tap 이벤트 리스너 관련이 없었기 때문에 추가 요청 드립니다

**Comment by dolphin2410** [comment]
디스코드 링크 수정  완료

**Comment by dolphin2410** [comment]
지금 EntityEvent 문서 작성중^^

**Comment by faiz36** [comment]
오 감사합니다 확인해볼게요

**Comment by faiz36** [comment]
![image](https://user-images.githubusercontent.com/79878012/214495782-30bcb324-b26e-494e-8b33-fd8915ebb22d.png)
혹시 이부분 클래스 이름 damagee는 고의인가요...? @dolphin2410
