### ISSUE TITLE
[Document Enhancement] Server Setup 관련.

### ISSUE THREAD

**Issue by issac4892** [monun-docs/monun-docs#8]
기본적으로 아록수님 서버스크립트나 각님꺼 기준으로 설명하는게 나을거 같은데

**Comment by patrick-choe** [comment]
서버스크립트는 개인 취향 많이 타는 부분이기도 하고 그래서 갠적으로는 바이너리 방식의 스크립트보다는 각별님이 만든 서버스크립트 파일이 나은거 같고...

서버스크립트에 대한 설명이랑, 커스텀하는 방법, 직접 콘솔 통해서 (클래식하게) 실행하는 방법 등을 설명해주면 될 것 같은데

**Comment by issac4892** [comment]
그럼 @patrick-choe 님이 다 하는거로 ㅋㅋㅋ
... 는 아니고 그러케 하져

**Comment by qogusdn1017** [comment]
> 그럼 @patrick-choe 님이 다 하는거로 ㅋㅋㅋ
> ... 는 아니고 그러케 하져

패트릭형이랑 나랑 시간내서 같이할까?

**Comment by patrick-choe** [comment]
> > 그럼 @patrick-choe 님이 다 하는거로 ㅋㅋㅋ
> > ... 는 아니고 그러케 하져
> 
> 패트릭형이랑 나랑 시간내서 같이할까?

ㅇㅋ 오늘 바로 할까?

**Comment by issac4892** [comment]
ㅇㅇ 그게 낫지 않을가

**Comment by qogusdn1017** [comment]
This issue is on WIP.

**Comment by qogusdn1017** [comment]
@patrick-choe @issac4892
Server-script is being updated due to PaperMC API Changes.

It should be updated soon.

**Comment by qogusdn1017** [comment]
- https://clip.aroxu.me/ 이거 넣어도될거같은데

**Comment by qogusdn1017** [comment]
ㅇㅋ
