### ISSUE TITLE
도메인 비활성화?

### ISSUE THREAD

**Issue by gooddltmdqls** [monun-docs/monun-docs#93]
문서를 읽기 위해 monun.me에 들어갔으나, 리다이렉팅의 경우에는 아예 접속이 되지 않고, 직접 입력하여 들어갔을 때에는 namecheap 도메인 판매 페이지가 나왔습니다.
![image](https://user-images.githubusercontent.com/45111740/170015239-735dfcb9-565d-4f52-ae53-5d4f5e8399ac.png)

**Comment by gooddltmdqls** [comment]
https://monun-docs.netlify.app 의 경우에는 접속이 가능합니다.

**Comment by dolphin2410** [comment]
지금 이 프로젝트 전 관리자 되시던 분이 이 프로젝트에서 활동을 안하셔서 도메인은 당분간은 못 사용할 것 같습니다. 일단 당분간은 [https://monun-docs.netlify.app/](https://monun-docs.netlify.app/)에서 확인하셔야 할 듯 합니다.

**Comment by qogusdn1017** [comment]
민건아 도메인 Grace Period 언제까지니

**Comment by qogusdn1017** [comment]
도메인 돈 되면 새로 사겠음? 몰?루

**Comment by issac4892** [comment]
아맞다

**Comment by issac4892** [comment]
![image](https://user-images.githubusercontent.com/56223465/171900492-cd8d289f-fa81-4270-9cab-aebc72e84664.png)
완료되면 다시 활성화하겠슴다

**Comment by issac4892** [comment]
![9BE4AF50-4754-4D44-9EF3-1015F9D085B4](https://user-images.githubusercontent.com/56223465/171909457-2556e8c8-a3bd-46d8-8f8e-c00eaf23555d.png)
완료

**Comment by qogusdn1017** [comment]
> ![image](https://user-images.githubusercontent.com/56223465/171900492-cd8d289f-fa81-4270-9cab-aebc72e84664.png) 완료되면 다시 활성화하겠슴다

어디로 이전한거고 얼마들음?

**Comment by issac4892** [comment]
구글 20달러
